#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
GIT_PARAMS="--git-dir=$SCRIPT_DIR/.git/ --work-tree=$SCRIPT_DIR/"
HAL_DIR="/home/hal/projects/lm1"

#echo "git add ."
git add .

#echo "git commit -m "
git commit -m "$@"

#echo "git push"
git push

#echo "sudo -u hal git --git-dir=$HAL_DIR/.git/ --work-tree=$HAL_DIR/ pull"
sudo -u hal git --git-dir=$HAL_DIR/.git/ --work-tree=$HAL_DIR/ pull
